bodies:
  robot:
    name: jackal
    pos: [50, 100]
    pose: 90
    bodies:
      - name: hokuyo
        pos: [0, 0, 0.1]
        type: lidar
      - name: zed
        pos: [0.2, 0, 0.15]
        type: camera
